<?php
/**
 * @file
 * Code for the CRF Humanitarian Bulletin feature.
 */

include_once 'crf_humanitarian_bulletin.features.inc';


/**
 * Implements hook_form_FORM_ID_alter().
 */
function crf_humanitarian_bulletin_form_humanitarian_bulletin_node_form_alter(&$form, &$form_state, $form_id) {
  $node = $form['#node'];
  if (!isset($node->nid)) {  
    $form['actions']['submit']['#value'] = t('Submit to OCHA');
  }
}